service: bertly

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-domain-manager

custom:
  clickTableName: 'bertly-clicks-${self:provider.stage}'
  wsgi:
    app: bertly.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
  customDomain:
    domainName: dosome.click
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-1
  profile: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "ClickDynamoDBTable", "Arn" ] }
  environment:
    CLICK_TABLE: ${self:custom.clickTableName}
    COMPOSE_REDIS_URL: '${ssm:bertly-redis-url}'

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    ClickDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: click_key
            AttributeType: S
        KeySchema:
          -
            AttributeName: click_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1 # Translates roughly to requests per second
          WriteCapacityUnits: 20
        TableName: ${self:custom.clickTableName}
