"""Create 'clicks' table

Revision ID: 37ba37319784
Revises:
Create Date: 2018-05-04 22:12:07.311844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba37319784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('click_id', sa.String(length=128), nullable=False),
    sa.Column('click_time', sa.DateTime(), nullable=True),
    sa.Column('shortened', sa.String(length=32), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('click_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clicks')
    # ### end Alembic commands ###
